# Generated by Django 4.2.30 on 2026-06-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="device_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name="student",
            constraint=models.UniqueConstraint(
                fields=("name", "device_id"), name="unique_student_name_per_device"
            ),
        ),
    ]
