# Generated by Django 4.2.30 on 2026-06-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="difficulty_level",
            field=models.CharField(blank=True, default="Beginner", max_length=20),
        ),
    ]
